REGION=""
POOL_ID=""
CLIENT_ID=""
IDENTITY_POOL_ID=""
GOOGLE_MAPS_KEY=""
BASE_URL=""
CUSTOM_DOMAIN=".hirtahealthconnector.com"
cd dashboard_website
npx webpack --env REGION=$REGION POOL_ID=$POOL_ID CLIENT_ID=$CLIENT_ID  IDENTITY_POOL_ID=$IDENTITY_POOL_ID GOOGLE_MAPS_KEY=$GOOGLE_MAPS_KEY BASE_URL=$BASE_URL CUSTOM_DOMAIN=$CUSTOM_DOMAIN
 
