REGION="us-east-1"
POOL_ID=""
CLIENT_ID=""
IDENTITY_POOL_ID=""
GOOGLE_MAPS_KEY=""
BASE_URL=""
cd dashboard_website
npx webpack --env REGION=$REGION POOL_ID=$POOL_ID CLIENT_ID=$CLIENT_ID  IDENTITY_POOL_ID=$IDENTITY_POOL_ID GOOGLE_MAPS_KEY=$GOOGLE_MAPS_KEY BASE_URL=$BASE_URL
 
